# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cabinet Bompart
locale: fr-FR
email: contact@cabinetbompart.fr
name: "Marc Bompart"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cabinetbompart.fr" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/logo.png"

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint

social:
  links:
    - "https://www.linkedin.com/in/marc-bompart-5634925"

footer:
  links:
    - label: "06 71 25 59 31"
      icon: "fas fa-fw fa-phone-square-alt"
      url: "tel:+33671255931"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:contact@cabinetbompart.fr"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marc-bompart-5634925"

include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      layout: "splash"
      description: "Conseil en propriété industrielle en brevets. Mandataire en brevets Europeens. French and European patent attorney. Annecy (74) Haute-Savoie."
      excerpt: "Conseil en propriété industrielle en brevets<br/>Mandataire en brevets Europeens<br/>French and European patent attorney"
      header:
        overlay_image: "/assets/images/bridge.png"
        overlay_color: "#7C77B9"
        overlay_filter: "0.5"
        show_overlay_excerpt: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

